const PaymentHistory = require('../models/PaymentHistory');

/**
 * Add calendar months to a date, keeping the same day-of-month where possible.
 * If the target month is shorter, clamp to the last day.
 */
function addMonths(date, months) {
  const result = new Date(date);
  const targetMonth = result.getMonth() + months;
  const targetYear = result.getFullYear() + Math.floor(targetMonth / 12);
  const normalizedMonth = ((targetMonth % 12) + 12) % 12;
  const originalDay = result.getDate();

  result.setFullYear(targetYear, normalizedMonth, 1);

  // Clamp to last day of target month if original day doesn't exist
  const lastDayOfMonth = new Date(targetYear, normalizedMonth + 1, 0).getDate();
  result.setDate(Math.min(originalDay, lastDayOfMonth));

  return result;
}

/**
 * Get the next payment date based on billing cycle.
 */
function getNextDate(currentDate, billingCycle, customCycleDays) {
  switch (billingCycle) {
    case 'daily':
      return new Date(currentDate.getTime() + 1 * 24 * 60 * 60 * 1000);
    case 'weekly':
      return new Date(currentDate.getTime() + 7 * 24 * 60 * 60 * 1000);
    case 'monthly':
      return addMonths(currentDate, 1);
    case 'quarterly':
      return addMonths(currentDate, 3);
    case 'yearly':
      return addMonths(currentDate, 12);
    case 'custom':
      return new Date(currentDate.getTime() + customCycleDays * 24 * 60 * 60 * 1000);
    default:
      return addMonths(currentDate, 1);
  }
}

/**
 * Generate payment schedule for a subscription.
 * Creates PaymentHistory documents for 12 months forward from today.
 * Handles trial periods: payments before trialEndDate use trialCost, after use regular cost.
 *
 * @param {Object} subscription - Mongoose Subscription document
 * @param {Date} [fromDate] - Optional date to start generating from (for regeneration)
 * @returns {Array} Created PaymentHistory documents
 */
async function generateSchedule(subscription, fromDate = null) {
  // Don't generate if subscription is not active
  if (subscription.status !== 'active') {
    return [];
  }

  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const maxDate = new Date(now);
  maxDate.setMonth(maxDate.getMonth() + 12);

  const paymentOperations = [];
  const scheduledDates = [];
  let currentDate = new Date(fromDate || subscription.startDate);

  while (currentDate <= maxDate) {
    // Historical dates must not be created as new scheduled payments.
    if (currentDate >= today) {
      const date = new Date(currentDate);
      scheduledDates.push(date);
      paymentOperations.push({
        updateOne: {
          filter: {
            subscription: subscription._id,
            date,
            status: 'scheduled',
            autoGenerated: true,
          },
          update: {
            $set: {
              user: subscription.user,
              amount: subscription.cost,
              status: 'scheduled',
              autoGenerated: true,
            },
            $setOnInsert: { subscription: subscription._id, date },
          },
          upsert: true,
        },
      });
    }

    currentDate = getNextDate(currentDate, subscription.billingCycle, subscription.customCycleDays);
  }

  if (paymentOperations.length === 0) {
    subscription.nextPaymentDate = null;
    await subscription.save();
    return [];
  }

  // Upsert before removing stale rows so an error cannot leave an empty
  // schedule. A unique subscription/date index prevents duplicates.
  await PaymentHistory.bulkWrite(paymentOperations, { ordered: true });
  const savedPayments = await PaymentHistory.find({
    subscription: subscription._id,
    status: 'scheduled',
    autoGenerated: true,
    date: { $in: scheduledDates },
  }).sort({ date: 1 });

  // Set nextPaymentDate to the first scheduled payment
  subscription.nextPaymentDate = savedPayments[0].date;
  await subscription.save();

  return savedPayments;
}

/**
 * Cancel all scheduled payments for a subscription.
 * Sets status to 'cancelled' for all scheduled payments.
 */
async function cancelScheduledPayments(subscriptionId) {
  await PaymentHistory.updateMany(
    { subscription: subscriptionId, status: 'scheduled' },
    { status: 'cancelled' }
  );
}

/**
 * Regenerate schedule from nextPaymentDate onwards.
 * Recreates future scheduled payments without deleting the old schedule first.
 */
async function regenerateSchedule(subscription) {
  // Regenerate from nextPaymentDate or startDate.
  const fromDate = subscription.nextPaymentDate || subscription.startDate;
  const payments = await generateSchedule(subscription, fromDate);
  const generatedDates = payments.map((payment) => payment.date);

  // Remove only obsolete auto-generated entries, after the replacement
  // schedule has been persisted. Manually managed payments are preserved.
  await PaymentHistory.deleteMany({
    subscription: subscription._id,
    status: 'scheduled',
    autoGenerated: true,
    date: { $gte: new Date(), $nin: generatedDates },
  });

  const nextPayment = await PaymentHistory.findOne({
    subscription: subscription._id,
    status: 'scheduled',
  }).sort({ date: 1 });
  subscription.nextPaymentDate = nextPayment ? nextPayment.date : null;
  await subscription.save();

  return payments;
}

module.exports = {
  generateSchedule,
  cancelScheduledPayments,
  regenerateSchedule,
  getNextDate,
  addMonths,
};
