const PaymentHistory = require('../models/PaymentHistory');

/**
 * Add calendar months to a date, keeping the same day-of-month where possible.
 * If the target month is shorter, clamp to the last day.
 */
function addMonths(date, months) {
  const result = new Date(date);
  const targetMonth = result.getMonth() + months;
  const targetYear = result.getFullYear() + Math.floor(targetMonth / 12);
  const normalizedMonth = ((targetMonth % 12) + 12) % 12;
  const originalDay = result.getDate();

  result.setFullYear(targetYear, normalizedMonth, 1);

  // Clamp to last day of target month if original day doesn't exist
  const lastDayOfMonth = new Date(targetYear, normalizedMonth + 1, 0).getDate();
  result.setDate(Math.min(originalDay, lastDayOfMonth));

  return result;
}

/**
 * Get the next payment date based on billing cycle.
 */
function getNextDate(currentDate, billingCycle, customCycleDays) {
  switch (billingCycle) {
    case 'daily':
      return new Date(currentDate.getTime() + 1 * 24 * 60 * 60 * 1000);
    case 'weekly':
      return new Date(currentDate.getTime() + 7 * 24 * 60 * 60 * 1000);
    case 'monthly':
      return addMonths(currentDate, 1);
    case 'quarterly':
      return addMonths(currentDate, 3);
    case 'yearly':
      return addMonths(currentDate, 12);
    case 'custom':
      return new Date(currentDate.getTime() + customCycleDays * 24 * 60 * 60 * 1000);
    default:
      return addMonths(currentDate, 1);
  }
}

/**
 * Generate payment schedule for a subscription.
 * Creates PaymentHistory documents for 12 months forward from startDate.
 * Handles trial periods: payments before trialEndDate use trialCost, after use regular cost.
 *
 * @param {Object} subscription - Mongoose Subscription document
 * @param {Date} [fromDate] - Optional date to start generating from (for regeneration)
 * @returns {Array} Created PaymentHistory documents
 */
async function generateSchedule(subscription, fromDate = null) {
  // Don't generate if subscription is not active
  if (subscription.status !== 'active') {
    return [];
  }

  const startDate = fromDate || subscription.startDate;
  const now = new Date();
  const maxDate = new Date(now);
  maxDate.setMonth(maxDate.getMonth() + 12);

  const payments = [];
  let currentDate = new Date(startDate);

  // Skip past dates that are before the start of our generation window
  // but only if fromDate was explicitly set (regeneration case)
  if (fromDate) {
    currentDate = new Date(fromDate);
  }

  while (currentDate <= maxDate) {
    const amount = subscription.cost;

    // Only create payments with date >= today (don't schedule in the past)
    if (currentDate >= now || !fromDate) {
      const payment = new PaymentHistory({
        subscription: subscription._id,
        user: subscription.user,
        amount,
        date: new Date(currentDate),
        status: 'scheduled',
        autoGenerated: true,
      });

      payments.push(payment);
    }

    currentDate = getNextDate(currentDate, subscription.billingCycle, subscription.customCycleDays);
  }

  if (payments.length === 0) {
    return [];
  }

  // Save all payment documents
  const savedPayments = await PaymentHistory.insertMany(payments);

  // Set nextPaymentDate to the first scheduled payment
  subscription.nextPaymentDate = savedPayments[0].date;
  await subscription.save();

  return savedPayments;
}

/**
 * Cancel all scheduled payments for a subscription.
 * Sets status to 'cancelled' for all scheduled payments.
 */
async function cancelScheduledPayments(subscriptionId) {
  await PaymentHistory.updateMany(
    { subscription: subscriptionId, status: 'scheduled' },
    { status: 'cancelled' }
  );
}

/**
 * Regenerate schedule from nextPaymentDate onwards.
 * Deletes future scheduled payments and recreates them.
 */
async function regenerateSchedule(subscription) {
  // Delete all future scheduled payments
  await PaymentHistory.deleteMany({
    subscription: subscription._id,
    status: 'scheduled',
  });

  // Regenerate from nextPaymentDate or startDate
  const fromDate = subscription.nextPaymentDate || subscription.startDate;

  return generateSchedule(subscription, fromDate);
}

module.exports = {
  generateSchedule,
  cancelScheduledPayments,
  regenerateSchedule,
  getNextDate,
  addMonths,
};
