const mongoose = require('mongoose');

const paymentHistorySchema = new mongoose.Schema({
  subscription: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Subscription',
    required: [true, 'Subscription is required'],
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'User is required'],
  },
  amount: {
    type: Number,
    required: [true, 'Amount is required'],
    min: [0, 'Amount cannot be negative'],
  },
  date: {
    type: Date,
    required: [true, 'Date is required'],
  },
  status: {
    type: String,
    enum: ['scheduled', 'paid', 'missed', 'cancelled'],
    default: 'scheduled',
  },
  autoGenerated: {
    type: Boolean,
    default: true,
  },
});

// Index for faster queries
paymentHistorySchema.index({ user: 1, date: 1 });
paymentHistorySchema.index({ subscription: 1 });
paymentHistorySchema.index({ user: 1, status: 1 });

module.exports = mongoose.model('PaymentHistory', paymentHistorySchema);
